export const assessmentQuestions = [
  {
    id: "interests",
    question: "What areas interest you most?",
    description: "Select all that apply to help us understand your passions",
    type: "multiple",
    options: [
      { value: "technology", label: "Technology & Innovation" },
      { value: "design", label: "Design & Creativity" },
      { value: "business", label: "Business & Strategy" },
      { value: "healthcare", label: "Healthcare & Medicine" },
      { value: "education", label: "Education & Teaching" },
      { value: "finance", label: "Finance & Economics" },
      { value: "marketing", label: "Marketing & Communications" },
      { value: "research", label: "Research & Analysis" },
    ],
  },
  {
    id: "work_environment",
    question: "What type of work environment do you prefer?",
    description: "Choose the option that best describes your ideal workplace",
    type: "single",
    options: [
      { value: "office", label: "Traditional office environment" },
      { value: "remote", label: "Remote/work from home" },
      { value: "hybrid", label: "Hybrid (mix of office and remote)" },
      { value: "field", label: "Field work/on-site with clients" },
      { value: "startup", label: "Fast-paced startup environment" },
    ],
  },
  {
    id: "career_goals",
    question: "What are your primary career goals?",
    description: "Select all that are important to you",
    type: "multiple",
    options: [
      { value: "high_salary", label: "High earning potential ($100K+)" },
      { value: "work_life_balance", label: "Good work-life balance" },
      { value: "growth", label: "Rapid career advancement" },
      { value: "impact", label: "Making a positive impact on society" },
      { value: "stability", label: "Job security and stability" },
      { value: "flexibility", label: "Flexible schedule and autonomy" },
      { value: "learning", label: "Continuous learning opportunities" },
      { value: "creativity", label: "Creative expression and innovation" },
    ],
  },
  {
    id: "education_level",
    question: "What is your highest level of education?",
    description: "Select your current educational background",
    type: "single",
    options: [
      { value: "high_school", label: "High School Diploma" },
      { value: "associate", label: "Associate Degree" },
      { value: "bachelor", label: "Bachelor's Degree" },
      { value: "master", label: "Master's Degree" },
      { value: "doctorate", label: "Doctorate/PhD" },
      { value: "bootcamp", label: "Coding Bootcamp/Certificate Program" },
      { value: "self_taught", label: "Self-taught/Online Learning" },
    ],
  },
]

// Comprehensive interest-based questions with detailed assessments
export const interestBasedQuestions = {
  technology: [
    {
      id: "tech_focus",
      question: "Which technology areas excite you most?",
      description: "Select your preferred technology domains (choose 2-4 for best results)",
      type: "multiple",
      options: [
        { value: "web_development", label: "Web Development (Frontend/Backend)" },
        { value: "mobile_development", label: "Mobile App Development" },
        { value: "data_science", label: "Data Science & Analytics" },
        { value: "ai_ml", label: "Artificial Intelligence & Machine Learning" },
        { value: "cybersecurity", label: "Cybersecurity & Information Security" },
        { value: "cloud_computing", label: "Cloud Computing & DevOps" },
        { value: "game_development", label: "Game Development" },
        { value: "blockchain", label: "Blockchain & Cryptocurrency" },
        { value: "iot", label: "Internet of Things (IoT)" },
        { value: "robotics", label: "Robotics & Automation" },
      ],
    },
    {
      id: "tech_skills",
      question: "Rate your current technical skills",
      description: "Be honest about your current abilities (1 = No experience, 5 = Expert level)",
      type: "rating",
      options: [
        { value: "programming", label: "Programming Languages (Python, JavaScript, Java, etc.)" },
        { value: "databases", label: "Database Management (SQL, NoSQL)" },
        { value: "system_design", label: "System Architecture & Design" },
        { value: "problem_solving", label: "Technical Problem Solving" },
        { value: "debugging", label: "Debugging & Troubleshooting" },
        { value: "version_control", label: "Version Control (Git)" },
      ],
    },
    {
      id: "tech_experience",
      question: "What is your experience level in technology?",
      description: "Choose the option that best describes your background",
      type: "single",
      options: [
        { value: "complete_beginner", label: "Complete beginner - no coding experience" },
        { value: "learning", label: "Currently learning - taking courses or tutorials" },
        { value: "hobbyist", label: "Hobbyist - personal projects and experimentation" },
        { value: "some_professional", label: "Some professional experience (1-2 years)" },
        { value: "experienced", label: "Experienced professional (3-5 years)" },
        { value: "senior", label: "Senior level (5+ years with leadership)" },
      ],
    },
    {
      id: "tech_learning_style",
      question: "How do you prefer to learn new technologies?",
      description: "Select your preferred learning approaches",
      type: "multiple",
      options: [
        { value: "hands_on", label: "Hands-on coding and building projects" },
        { value: "structured_courses", label: "Structured online courses and tutorials" },
        { value: "documentation", label: "Reading documentation and technical guides" },
        { value: "mentorship", label: "Learning from mentors and senior developers" },
        { value: "community", label: "Community forums and peer learning" },
        { value: "bootcamps", label: "Intensive bootcamps and workshops" },
      ],
    },
  ],
  design: [
    {
      id: "design_focus",
      question: "Which design areas appeal to you most?",
      description: "Select your design interests (choose 2-4 for best results)",
      type: "multiple",
      options: [
        { value: "ui_ux", label: "UI/UX Design for Digital Products" },
        { value: "graphic_design", label: "Graphic Design & Visual Communication" },
        { value: "product_design", label: "Product Design & Industrial Design" },
        { value: "web_design", label: "Web Design & Digital Interfaces" },
        { value: "brand_design", label: "Brand & Identity Design" },
        { value: "motion_graphics", label: "Motion Graphics & Animation" },
        { value: "interior_design", label: "Interior & Spatial Design" },
        { value: "fashion_design", label: "Fashion & Textile Design" },
        { value: "service_design", label: "Service Design & Experience Design" },
      ],
    },
    {
      id: "design_skills",
      question: "Rate your design capabilities",
      description: "Assess your current design skills (1 = Beginner, 5 = Expert)",
      type: "rating",
      options: [
        { value: "visual_design", label: "Visual Design & Aesthetics" },
        { value: "user_research", label: "User Research & Testing" },
        { value: "prototyping", label: "Prototyping & Wireframing" },
        { value: "design_thinking", label: "Design Thinking Process" },
        { value: "color_theory", label: "Color Theory & Typography" },
        { value: "design_tools", label: "Design Software Proficiency" },
      ],
    },
    {
      id: "design_approach",
      question: "What's your design philosophy?",
      description: "Choose the approach that resonates with you most",
      type: "single",
      options: [
        { value: "user_centered", label: "User-centered design - prioritizing user needs" },
        { value: "aesthetic_focused", label: "Aesthetic-focused - creating beautiful visuals" },
        { value: "problem_solving", label: "Problem-solving - design as solution finding" },
        { value: "minimalist", label: "Minimalist - less is more approach" },
        { value: "experimental", label: "Experimental - pushing creative boundaries" },
        { value: "data_driven", label: "Data-driven - decisions based on metrics" },
      ],
    },
    {
      id: "design_tools",
      question: "Which design tools are you familiar with?",
      description: "Select all tools you have experience with",
      type: "multiple",
      options: [
        { value: "figma", label: "Figma" },
        { value: "sketch", label: "Sketch" },
        { value: "adobe_creative", label: "Adobe Creative Suite (Photoshop, Illustrator, etc.)" },
        { value: "canva", label: "Canva" },
        { value: "invision", label: "InVision/Marvel" },
        { value: "principle", label: "Principle/Framer" },
        { value: "blender", label: "Blender/3D Software" },
        { value: "none", label: "None - I'm just starting" },
      ],
    },
  ],
  business: [
    {
      id: "business_focus",
      question: "Which business areas interest you most?",
      description: "Select your business focus areas (choose 2-4 for best results)",
      type: "multiple",
      options: [
        { value: "management", label: "Management & Leadership" },
        { value: "consulting", label: "Business Consulting & Strategy" },
        { value: "entrepreneurship", label: "Entrepreneurship & Startups" },
        { value: "operations", label: "Operations & Process Management" },
        { value: "strategy", label: "Strategic Planning & Analysis" },
        { value: "project_management", label: "Project & Program Management" },
        { value: "sales", label: "Sales & Business Development" },
        { value: "hr", label: "Human Resources & Talent Management" },
        { value: "supply_chain", label: "Supply Chain & Logistics" },
      ],
    },
    {
      id: "business_skills",
      question: "Rate your business skills",
      description: "Assess your business capabilities (1 = Beginner, 5 = Expert)",
      type: "rating",
      options: [
        { value: "leadership", label: "Leadership & Team Management" },
        { value: "communication", label: "Communication & Presentation" },
        { value: "strategic_thinking", label: "Strategic & Analytical Thinking" },
        { value: "negotiation", label: "Negotiation & Persuasion" },
        { value: "financial_analysis", label: "Financial Analysis & Budgeting" },
        { value: "project_management", label: "Project Management" },
      ],
    },
    {
      id: "business_experience",
      question: "What is your business experience level?",
      description: "Choose your level of business experience",
      type: "single",
      options: [
        { value: "student", label: "Student - studying business or related field" },
        { value: "entry_level", label: "Entry level - 0-2 years professional experience" },
        { value: "mid_level", label: "Mid-level - 2-5 years experience" },
        { value: "senior_level", label: "Senior level - 5-10 years experience" },
        { value: "executive", label: "Executive level - 10+ years with leadership roles" },
        { value: "entrepreneur", label: "Entrepreneur - started own business(es)" },
      ],
    },
    {
      id: "business_environment",
      question: "What type of business environment appeals to you?",
      description: "Select your preferred business settings",
      type: "multiple",
      options: [
        { value: "corporate", label: "Large corporations with established processes" },
        { value: "startup", label: "Fast-paced startups with high growth potential" },
        { value: "consulting", label: "Consulting firms working with diverse clients" },
        { value: "nonprofit", label: "Non-profit organizations with social impact" },
        { value: "government", label: "Government agencies and public sector" },
        { value: "family_business", label: "Family-owned businesses" },
      ],
    },
  ],
  healthcare: [
    {
      id: "healthcare_focus",
      question: "Which healthcare areas interest you most?",
      description: "Select your healthcare focus areas (choose 2-4 for best results)",
      type: "multiple",
      options: [
        { value: "clinical_care", label: "Direct Patient Care & Clinical Practice" },
        { value: "medical_research", label: "Medical Research & Clinical Trials" },
        { value: "public_health", label: "Public Health & Epidemiology" },
        { value: "health_tech", label: "Health Technology & Digital Health" },
        { value: "mental_health", label: "Mental Health & Psychology" },
        { value: "administration", label: "Healthcare Administration & Management" },
        { value: "pharmacy", label: "Pharmacy & Pharmaceutical Sciences" },
        { value: "nursing", label: "Nursing & Patient Care" },
        { value: "therapy", label: "Physical/Occupational Therapy" },
        { value: "health_policy", label: "Health Policy & Healthcare Systems" },
      ],
    },
    {
      id: "healthcare_skills",
      question: "Rate your healthcare-related skills",
      description: "Assess your capabilities (1 = No experience, 5 = Expert)",
      type: "rating",
      options: [
        { value: "patient_care", label: "Patient Care & Bedside Manner" },
        { value: "medical_knowledge", label: "Medical Knowledge & Sciences" },
        { value: "empathy", label: "Empathy & Emotional Intelligence" },
        { value: "attention_to_detail", label: "Attention to Detail & Accuracy" },
        { value: "crisis_management", label: "Crisis Management & Decision Making" },
        { value: "communication", label: "Healthcare Communication" },
      ],
    },
    {
      id: "healthcare_motivation",
      question: "What motivates you most about healthcare?",
      description: "Choose your primary motivation",
      type: "single",
      options: [
        { value: "helping_people", label: "Directly helping people and saving lives" },
        { value: "scientific_discovery", label: "Scientific discovery and medical advancement" },
        { value: "problem_solving", label: "Complex problem-solving and diagnosis" },
        { value: "technology_innovation", label: "Healthcare technology and innovation" },
        { value: "community_impact", label: "Community health and population impact" },
        { value: "research_advancement", label: "Research and evidence-based practice" },
      ],
    },
  ],
  marketing: [
    {
      id: "marketing_focus",
      question: "Which marketing areas appeal to you most?",
      description: "Select your marketing interests (choose 2-4 for best results)",
      type: "multiple",
      options: [
        { value: "digital_marketing", label: "Digital Marketing & Online Advertising" },
        { value: "content_marketing", label: "Content Marketing & Storytelling" },
        { value: "social_media", label: "Social Media Marketing & Community" },
        { value: "brand_marketing", label: "Brand Marketing & Strategy" },
        { value: "email_marketing", label: "Email Marketing & Automation" },
        { value: "seo_sem", label: "SEO/SEM & Search Marketing" },
        { value: "analytics", label: "Marketing Analytics & Data Science" },
        { value: "pr", label: "Public Relations & Communications" },
        { value: "event_marketing", label: "Event Marketing & Experiential" },
        { value: "influencer_marketing", label: "Influencer & Partnership Marketing" },
      ],
    },
    {
      id: "marketing_skills",
      question: "Rate your marketing skills",
      description: "Assess your marketing capabilities (1 = Beginner, 5 = Expert)",
      type: "rating",
      options: [
        { value: "creativity", label: "Creative Thinking & Campaign Development" },
        { value: "analytics", label: "Data Analysis & Performance Metrics" },
        { value: "communication", label: "Written & Verbal Communication" },
        { value: "strategy", label: "Strategic Planning & Market Research" },
        { value: "digital_tools", label: "Digital Marketing Tools & Platforms" },
        { value: "customer_psychology", label: "Consumer Psychology & Behavior" },
      ],
    },
    {
      id: "marketing_approach",
      question: "What's your preferred marketing approach?",
      description: "Choose the style that resonates with you",
      type: "single",
      options: [
        { value: "data_driven", label: "Data-driven - decisions based on analytics" },
        { value: "creative_storytelling", label: "Creative storytelling - emotional connection" },
        { value: "growth_hacking", label: "Growth hacking - rapid experimentation" },
        { value: "relationship_building", label: "Relationship building - long-term engagement" },
        { value: "performance_focused", label: "Performance-focused - ROI optimization" },
        { value: "brand_building", label: "Long-term brand equity" },
      ],
    },
  ],
  finance: [
    {
      id: "finance_focus",
      question: "Which finance areas interest you most?",
      description: "Select your finance focus areas (choose 2-4 for best results)",
      type: "multiple",
      options: [
        { value: "investment_banking", label: "Investment Banking & Capital Markets" },
        { value: "financial_planning", label: "Financial Planning & Wealth Management" },
        { value: "accounting", label: "Accounting & Financial Reporting" },
        { value: "corporate_finance", label: "Corporate Finance & Treasury" },
        { value: "fintech", label: "Financial Technology & Innovation" },
        { value: "insurance", label: "Insurance & Risk Management" },
        { value: "real_estate", label: "Real Estate Finance & Investment" },
        { value: "trading", label: "Trading & Portfolio Management" },
        { value: "financial_analysis", label: "Financial Analysis & Research" },
        { value: "compliance", label: "Financial Compliance & Regulation" },
      ],
    },
    {
      id: "finance_skills",
      question: "Rate your finance skills",
      description: "Assess your financial capabilities (1 = Beginner, 5 = Expert)",
      type: "rating",
      options: [
        { value: "analytical_thinking", label: "Analytical & Quantitative Thinking" },
        { value: "attention_to_detail", label: "Attention to Detail & Accuracy" },
        { value: "mathematical_skills", label: "Mathematical & Statistical Skills" },
        { value: "risk_assessment", label: "Risk Assessment & Management" },
        { value: "financial_modeling", label: "Financial Modeling & Valuation" },
        { value: "market_knowledge", label: "Market Knowledge & Economic Understanding" },
      ],
    },
    {
      id: "finance_motivation",
      question: "What attracts you most to finance?",
      description: "Choose your primary motivation",
      type: "single",
      options: [
        { value: "wealth_creation", label: "Wealth creation and high earning potential" },
        { value: "analytical_challenge", label: "Analytical challenges and problem-solving" },
        { value: "market_dynamics", label: "Understanding market dynamics and economics" },
        { value: "helping_clients", label: "Helping clients achieve financial goals" },
        { value: "innovation", label: "Financial innovation and technology" },
        { value: "stability", label: "Career stability and professional prestige" },
      ],
    },
  ],
  education: [
    {
      id: "education_focus",
      question: "Which education areas interest you most?",
      description: "Select your education focus areas (choose 2-4 for best results)",
      type: "multiple",
      options: [
        { value: "k12_teaching", label: "K-12 Teaching & Classroom Instruction" },
        { value: "higher_education", label: "Higher Education & University Teaching" },
        { value: "curriculum_design", label: "Curriculum Design & Educational Content" },
        { value: "educational_technology", label: "Educational Technology & E-Learning" },
        { value: "administration", label: "Educational Administration & Leadership" },
        { value: "special_education", label: "Special Education & Learning Disabilities" },
        { value: "online_learning", label: "Online Learning & Distance Education" },
        { value: "training_development", label: "Corporate Training & Professional Development" },
        { value: "educational_research", label: "Educational Research & Policy" },
      ],
    },
    {
      id: "education_skills",
      question: "Rate your education-related skills",
      description: "Assess your teaching capabilities (1 = Beginner, 5 = Expert)",
      type: "rating",
      options: [
        { value: "communication", label: "Clear Communication & Explanation" },
        { value: "patience", label: "Patience & Understanding" },
        { value: "creativity", label: "Creative Teaching Methods" },
        { value: "empathy", label: "Empathy & Emotional Intelligence" },
        { value: "organization", label: "Organization & Planning" },
        { value: "adaptability", label: "Adaptability to Different Learning Styles" },
      ],
    },
    {
      id: "education_level_preference",
      question: "Which education level appeals to you most?",
      description: "Choose your preferred student demographic",
      type: "single",
      options: [
        { value: "early_childhood", label: "Early childhood (Pre-K to Grade 2)" },
        { value: "elementary", label: "Elementary school (Grades 3-5)" },
        { value: "middle_school", label: "Middle school (Grades 6-8)" },
        { value: "high_school", label: "High school (Grades 9-12)" },
        { value: "college", label: "College/University students" },
        { value: "adult_learners", label: "Adult learners and continuing education" },
        { value: "corporate", label: "Corporate training and professional development" },
      ],
    },
  ],
  research: [
    {
      id: "research_focus",
      question: "Which research areas interest you most?",
      description: "Select your research focus areas (choose 2-4 for best results)",
      type: "multiple",
      options: [
        { value: "scientific_research", label: "Scientific Research & Laboratory Work" },
        { value: "market_research", label: "Market Research & Consumer Insights" },
        { value: "academic_research", label: "Academic Research & Publications" },
        { value: "user_research", label: "User Experience Research & Testing" },
        { value: "data_research", label: "Data Research & Statistical Analysis" },
        { value: "policy_research", label: "Policy Research & Government Studies" },
        { value: "medical_research", label: "Medical Research & Clinical Studies" },
        { value: "social_research", label: "Social Research & Behavioral Studies" },
        { value: "technology_research", label: "Technology Research & Development" },
      ],
    },
    {
      id: "research_skills",
      question: "Rate your research skills",
      description: "Assess your research capabilities (1 = Beginner, 5 = Expert)",
      type: "rating",
      options: [
        { value: "analytical_thinking", label: "Analytical & Critical Thinking" },
        { value: "attention_to_detail", label: "Attention to Detail & Precision" },
        { value: "data_analysis", label: "Data Analysis & Statistical Methods" },
        { value: "writing", label: "Research Writing & Documentation" },
        { value: "methodology", label: "Research Methodology & Design" },
        { value: "curiosity", label: "Intellectual Curiosity & Persistence" },
      ],
    },
    {
      id: "research_environment",
      question: "What research environment appeals to you?",
      description: "Choose your preferred research setting",
      type: "single",
      options: [
        { value: "academic", label: "Academic institutions and universities" },
        { value: "corporate", label: "Corporate R&D departments" },
        { value: "government", label: "Government agencies and labs" },
        { value: "nonprofit", label: "Non-profit research organizations" },
        { value: "startup", label: "Startup companies and innovation labs" },
        { value: "independent", label: "Independent research and consulting" },
      ],
    },
  ],
}

// Enhanced career matching with detailed scoring
export const careerMatching = {
  technology: {
    web_development: [
      { title: "Software Engineer", weight: 1.0, skills: ["programming", "problem_solving", "system_design"] },
      { title: "UX Designer", weight: 0.7, skills: ["programming", "visual_design", "user_research"] },
    ],
    mobile_development: [
      { title: "Software Engineer", weight: 0.9, skills: ["programming", "problem_solving", "user_research"] },
    ],
    data_science: [
      { title: "Data Scientist", weight: 1.0, skills: ["analytical_thinking", "programming", "data_analysis"] },
      {
        title: "Research Analyst",
        weight: 0.8,
        skills: ["analytical_thinking", "data_analysis", "attention_to_detail"],
      },
    ],
    ai_ml: [
      { title: "Data Scientist", weight: 1.0, skills: ["programming", "analytical_thinking", "data_analysis"] },
      { title: "Software Engineer", weight: 0.8, skills: ["programming", "analytical_thinking", "problem_solving"] },
    ],
    cybersecurity: [
      {
        title: "Cybersecurity Analyst",
        weight: 1.0,
        skills: ["analytical_thinking", "attention_to_detail", "problem_solving"],
      },
      { title: "Software Engineer", weight: 0.7, skills: ["programming", "analytical_thinking", "system_design"] },
    ],
    cloud_computing: [
      { title: "Software Engineer", weight: 0.9, skills: ["programming", "system_design", "problem_solving"] },
    ],
    // Add fallback for any unmatched tech focus
    general: [
      { title: "Software Engineer", weight: 0.8, skills: ["programming", "problem_solving"] },
      { title: "Data Scientist", weight: 0.7, skills: ["analytical_thinking", "programming"] },
    ],
  },
  design: {
    ui_ux: [
      { title: "UX Designer", weight: 1.0, skills: ["user_research", "design_thinking", "empathy"] },
      { title: "Product Designer", weight: 0.8, skills: ["design_thinking", "user_research", "strategic_thinking"] },
    ],
    graphic_design: [
      { title: "Graphic Designer", weight: 1.0, skills: ["visual_design", "creativity", "color_theory"] },
      { title: "UX Designer", weight: 0.6, skills: ["visual_design", "creativity", "design_tools"] },
    ],
    product_design: [
      { title: "Product Designer", weight: 1.0, skills: ["design_thinking", "user_research", "prototyping"] },
      { title: "UX Designer", weight: 0.8, skills: ["design_thinking", "user_research", "prototyping"] },
    ],
    web_design: [
      { title: "UX Designer", weight: 0.9, skills: ["visual_design", "user_research", "prototyping"] },
      { title: "Software Engineer", weight: 0.6, skills: ["programming", "visual_design", "problem_solving"] },
    ],
    general: [
      { title: "UX Designer", weight: 0.8, skills: ["design_thinking", "creativity"] },
      { title: "Graphic Designer", weight: 0.7, skills: ["visual_design", "creativity"] },
    ],
  },
  business: {
    management: [
      { title: "Project Manager", weight: 1.0, skills: ["leadership", "communication", "project_management"] },
      { title: "Business Analyst", weight: 0.7, skills: ["analytical_thinking", "communication", "problem_solving"] },
    ],
    consulting: [
      { title: "Business Analyst", weight: 1.0, skills: ["analytical_thinking", "communication", "problem_solving"] },
      { title: "Project Manager", weight: 0.8, skills: ["strategic_thinking", "communication", "leadership"] },
    ],
    entrepreneurship: [
      { title: "Project Manager", weight: 0.8, skills: ["leadership", "strategic_thinking", "creativity"] },
      { title: "Marketing Manager", weight: 0.7, skills: ["creativity", "strategic_thinking", "communication"] },
    ],
    sales: [
      { title: "Marketing Manager", weight: 0.9, skills: ["communication", "persuasion", "relationship_building"] },
      { title: "Business Analyst", weight: 0.6, skills: ["communication", "analytical_thinking", "problem_solving"] },
    ],
    general: [
      { title: "Project Manager", weight: 0.8, skills: ["leadership", "communication"] },
      { title: "Business Analyst", weight: 0.8, skills: ["analytical_thinking", "communication"] },
    ],
  },
  marketing: {
    digital_marketing: [
      { title: "Digital Marketing Specialist", weight: 1.0, skills: ["analytics", "creativity", "digital_tools"] },
      { title: "Marketing Manager", weight: 0.9, skills: ["creativity", "analytics", "communication"] },
    ],
    content_marketing: [
      { title: "Marketing Manager", weight: 1.0, skills: ["creativity", "communication", "strategy"] },
      { title: "Digital Marketing Specialist", weight: 0.8, skills: ["creativity", "communication", "digital_tools"] },
    ],
    social_media: [
      { title: "Digital Marketing Specialist", weight: 1.0, skills: ["creativity", "communication", "digital_tools"] },
      { title: "Marketing Manager", weight: 0.8, skills: ["communication", "creativity", "strategy"] },
    ],
    general: [
      { title: "Marketing Manager", weight: 0.8, skills: ["creativity", "communication"] },
      { title: "Digital Marketing Specialist", weight: 0.8, skills: ["digital_tools", "creativity"] },
    ],
  },
  finance: {
    investment_banking: [
      {
        title: "Financial Analyst",
        weight: 1.0,
        skills: ["analytical_thinking", "financial_modeling", "attention_to_detail"],
      },
    ],
    financial_planning: [
      {
        title: "Financial Analyst",
        weight: 1.0,
        skills: ["communication", "analytical_thinking", "attention_to_detail"],
      },
    ],
    accounting: [
      {
        title: "Financial Analyst",
        weight: 0.9,
        skills: ["attention_to_detail", "analytical_thinking", "mathematical_skills"],
      },
    ],
    general: [{ title: "Financial Analyst", weight: 0.8, skills: ["analytical_thinking", "attention_to_detail"] }],
  },
  healthcare: {
    clinical_care: [
      {
        title: "Healthcare Administrator",
        weight: 0.8,
        skills: ["leadership", "healthcare_knowledge", "communication"],
      },
    ],
    administration: [
      { title: "Healthcare Administrator", weight: 1.0, skills: ["leadership", "administration", "communication"] },
    ],
    health_tech: [
      {
        title: "Healthcare Administrator",
        weight: 0.7,
        skills: ["technology", "healthcare_knowledge", "problem_solving"],
      },
    ],
    general: [{ title: "Healthcare Administrator", weight: 0.8, skills: ["healthcare_knowledge", "communication"] }],
  },
  education: {
    k12_teaching: [{ title: "Teacher", weight: 1.0, skills: ["communication", "patience", "creativity"] }],
    higher_education: [
      { title: "Teacher", weight: 0.9, skills: ["communication", "subject_expertise", "organization"] },
    ],
    educational_technology: [{ title: "Teacher", weight: 0.7, skills: ["technology", "creativity", "communication"] }],
    general: [{ title: "Teacher", weight: 0.8, skills: ["communication", "patience"] }],
  },
  research: {
    scientific_research: [
      { title: "Research Analyst", weight: 1.0, skills: ["analytical_thinking", "methodology", "attention_to_detail"] },
    ],
    market_research: [
      { title: "Research Analyst", weight: 1.0, skills: ["analytical_thinking", "data_analysis", "communication"] },
      { title: "Business Analyst", weight: 0.8, skills: ["analytical_thinking", "data_analysis", "communication"] },
    ],
    user_research: [
      { title: "UX Designer", weight: 0.9, skills: ["user_research", "analytical_thinking", "empathy"] },
      { title: "Research Analyst", weight: 0.8, skills: ["research_methods", "analytical_thinking", "communication"] },
    ],
    general: [{ title: "Research Analyst", weight: 0.8, skills: ["analytical_thinking", "research_methods"] }],
  },
}

// Skill gap analysis and recommendations
export const skillDevelopmentPaths = {
  programming: {
    beginner: ["Learn basic programming concepts", "Choose a programming language", "Build simple projects"],
    intermediate: ["Learn data structures and algorithms", "Build complex applications", "Contribute to open source"],
    advanced: ["System design and architecture", "Lead development teams", "Mentor junior developers"],
  },
  design_thinking: {
    beginner: ["Learn design thinking process", "Practice user empathy", "Create basic wireframes"],
    intermediate: ["Conduct user research", "Build interactive prototypes", "Test with real users"],
    advanced: ["Lead design strategy", "Mentor design teams", "Drive design culture"],
  },
  analytical_thinking: {
    beginner: ["Learn basic statistics", "Practice data interpretation", "Use analytical tools"],
    intermediate: ["Advanced statistical methods", "Build analytical models", "Present insights effectively"],
    advanced: ["Strategic analysis", "Lead analytical teams", "Drive data-driven decisions"],
  },
  leadership: {
    beginner: ["Learn leadership fundamentals", "Practice team collaboration", "Take on small leadership roles"],
    intermediate: ["Manage teams effectively", "Develop others", "Handle conflicts"],
    advanced: ["Strategic leadership", "Organizational change", "Executive presence"],
  },
  communication: {
    beginner: ["Practice public speaking", "Improve writing skills", "Active listening"],
    intermediate: ["Presentation skills", "Cross-functional communication", "Stakeholder management"],
    advanced: ["Executive communication", "Thought leadership", "Crisis communication"],
  },
}
